function [fitresult, gof] = createPsychophysicsFit(ori, p4)
%createPsychophysicsFit(xdata,ydata)
%  Create a fit of psychophysical data (normcdf)
%
%  Data for 'fitting a s-shape' fit:
%      X Input : ori
%      Y Output: p4
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-May-2019 11:36:48


%% Fit: 'fitting a s-shape'.
[xData, yData] = prepareCurveData( ori, p4 );

% Set up fittype and options.
ft = fittype( 'normcdf(x,a,b)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.70245499971232 0.573306435053406];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'fitting a s-shape' );
h = plot( fitresult, xData, yData );
legend( h, 'p4 vs. ori', 'fitting a s-shape', 'Location', 'NorthEast' );
% Label axes
xlabel ori
ylabel p4
grid on


