%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Volumes/MATLAB2019/code/s1-psy.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/05/02 11:22:16

%% Initialize variables.
filename = '/Volumes/MATLAB2019/code/s1-psy.txt';
delimiter = '\t';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
ori = dataArray{:, 1};
p1 = dataArray{:, 2};
p2 = dataArray{:, 3};
p3 = dataArray{:, 4};
p4 = dataArray{:, 5};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;